name: comics_app
description: App for show comics

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  dio: ^4.0.6
  injectable: ^1.5.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  equatable: ^2.0.3
  http: ^0.13.4
  pretty_dio_logger: ^1.1.1
  intl: ^0.17.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  build_runner: ^2.1.11


  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

assets:
  - .env